### ISSUE TITLE
How to do inference in non-overlapping/overlapping community detection task?

### ISSUE THREAD

**Issue by MaKaili** [sunfanyunn/vGraph#1]
Hi fanyun,

Thanks for sharing the source code, and I have 2 questions. Hope get your reply.

1. I want to know how to do inference in 2 community detection tasks, computering the similarity between node embedding and community embedding? If so, we need to set a threshold in overlapping setting?

2. The ground truth of non-overlapping setting and node classifiction are the same, is it a description that node representation benefits to non-overlapping?

Best,
Kaili

**Comment by sunfanyunn** [comment]
1. I did not use thresholding to inference overlapping communities. Details are in the paper.
2. The result that vGraph outperforms many two-stage (node embedding + K-Means) methods on both tasks is a description that node representation benefits to non-overlapping community detection.
