### ISSUE TITLE
Hi guys, where I can find the dataset?just download from the standard??

### ISSUE THREAD

**Issue by momomom123** [sunfanyunn/vGraph#11]
🤗

**Comment by alip67** [comment]
I have the same question. could you please provide this information?

**Comment by sunfanyunn** [comment]
It is in the paper (Appendix).

**Comment by sunfanyunn** [comment]
https://linqs.soe.ucsc.edu/data
http://snap.stanford.edu/data/ego-Facebook.html
http://snap.stanford.edu/data/com-Youtube.html
http://snap.stanford.edu/data/com-Amazon.html
http://snap.stanford.edu/data/com-DBLP.html
https://www.aminer.org/aminernetwork
