### ISSUE TITLE
about context node embeddings

### ISSUE THREAD

**Issue by felixwzh** [sunfanyunn/vGraph#3]
Hi, thanks for sharing the code. I have a question about the context node embeddings. I noticed that in `nonoverlapping.py` the context node embeddings `self.contextnode_embeddings` was initialized:
https://github.com/fanyun-sun/vGraph/blob/2b69e4794128192da4ba25c4a219bd1a2e5bd855/nonoverlapping-community-detection/nonoverlapping.py#L127-L128
But was not assigned to the context embeddings `c` (I guess).
https://github.com/fanyun-sun/vGraph/blob/2b69e4794128192da4ba25c4a219bd1a2e5bd855/nonoverlapping-community-detection/nonoverlapping.py#L146-L147
Also, in `overlapping.py`, the `self.contextnode_embeddings`  has been commented:

https://github.com/fanyun-sun/vGraph/blob/2b69e4794128192da4ba25c4a219bd1a2e5bd855/overlapping-community-detection/overlapping.py#L134-L135
But in the paper (Section 4.1), it is said that 
> Note that different sets of node embeddings are used to parametrize the two distributions.

So my questions are 1) do we have to use context node embeddings or just use one set of node embeddings? 2) it seems that you also tried the one set of node embeddings setting, how is it?

**Comment by sunfanyunn** [comment]
Yes, we tried both.
In my experience, It does not yield much difference in performance.
