### ISSUE TITLE
Nonoverlapping datasets request

### ISSUE THREAD

**Issue by MhYao2014** [sunfanyunn/vGraph#4]
Where am I supposed to find the following data sets? Namely the "Cornell", "Texas", "Washington", and "Wisconsin" data sets. The footnote in appendix A of this paper's arxiv version only contains "Citeseer" and "Cora" data sets (https://linqs.soe.ucsc.edu).

**Comment by sunfanyunn** [comment]
All of them are subsets of WebkB dataset.

**Comment by MhYao2014** [comment]
Thanks, problem solved.
