### ISSUE TITLE
Negative Sampling

### ISSUE THREAD

**Issue by cezhang01** [sunfanyunn/vGraph#7]
Hi Fan-Yun,

Your paper is a great work! I would like to know that when you use negative sampling as LINE, what is the number of negative samples K in Equation 4? Thank you!

**Comment by sunfanyunn** [comment]
Thank you!
The results on the paper are acquired without negative sampling.
If you would like to use negative sampling, you can refer to this repo 
https://github.com/DMPierre/LINE (K = 5).
